#!/usr/bin/env python
# coding: utf-8

# - We will use the same example that we have already seen.
# - Numpy helps us to manipulate matrices


import numpy as np

revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

profit = revenue - expenses
profit


price_per_unit = np.array ([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])
revenue = price_per_unit * units
revenue


# - As you can see, the matrices are not of the same dimensions and therefore Numpy will duplicate [1000,400,1200] another 2 times by default, hence the result
# - This concept is called Broadcasting in Numpy

# In order to find the result, we will use the dot product function

revenue = np.dot(price_per_unit,units)
revenue
